### ISSUE TITLE
SmartSheet

### ISSUE THREAD

**Issue by salathiel1999** [SistemasTecTlaxiaco/actividad-8-planificacion-de-sprints-en-smartsheet-dream-team1#1]
[smartshet-1.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-planificacion-de-sprints-en-smartsheet-dream-team1/files/9906313/smartshet-1.pdf)

**Comment by josealfredo79** [comment]
Calificacion 26

**Comment by josealfredo79** [comment]
Revisado y bien hecho
